---
title: "New Project 2"
author: "Minh Pham"
date: "2/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Different survey design function




```{r}
library(readr)
library(lodown)
library(tidyverse)
library(survey)
library(zoo)
library(dplyr)
library(srvyr)

lodown( "brfss" , output_dir = file.path( path.expand( "~" ) , "BRFSS" ) )

# examine all available BRFSS microdata files
brfss_cat <-
    get_catalog( "brfss" ,
        output_dir = file.path( path.expand( "~" ) , "BRFSS" ) )

# 2017 only
brfss_cat <- subset( brfss_cat , year == 2017 )
# download the microdata to your local computer
brfss_cat <- lodown( "brfss" , brfss_cat )




#Note:
#DDEPEV2= Ever told you had a depressive disorder
#HLTHPLN1= Have any health care coverage
#cadult= Are you 18 years of age or older?
#numadult= Number of Adults in Household
#dispcode= Final Disposition with 1100 = Completed Interview, 1200 = Partial Complete Interview
#medcost= Could Not See Doctor Because of Cost
#asthnow= Do you still have asthma?
#ADDEPEV2= Ever told you had a depressive disorder?
#DIABETE3= (Ever told) you have diabetes
#VETERAN3= Are You A Veteran?
#EMPLOY1= Employment Status
#DECIDE= Difficulty Concentrating or Remembering. Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions?
#SMOKE100= Smoked at Least 100 Cigarettes
#SMOKDAY2= Frequency of Days Now Smoking
#STOPSMK2= Stopped Smoking in past 12 months
#USENOW3= Use of Smokeless Tobacco Products
#ALCDAY5= Days in past 30 had alcoholic beverage
#AVEDRNK2= Avg alcoholic drinks per day in past 30
#DRNK3GE5= Binge Drinking.Considering all types of alcoholic beverages, how many times during the past 30 days did you have 5 or more drinks for men or 4 or more drinks for women on an occasion?
#EXERANY2= Exercise in Past 30 Days
#EXEROFT1(2)= How Many Times Walking, Running, Jogging, or Swimming
#EXERHMM1(2)= Minutes or Hours Walking, Running, Jogging, or Swimming
#STRENGTH= How many times did you do physical activities or exercises to STRENGTHEN your muscles?
#COPDSMOK = How many years have you smoked tobacco products?
#SLEPTIM1= How Much Time Do You Sleep
#ADSLEEP= Over the last 2 weeks, how many days have you had trouble falling asleep or staying asleep or sleeping too much?
#MEDICARE= Do you have Medicare? (Medicare is a coverage plan for people 65 or over and for certain disabled people.)
#HLTHCVR1= What is the primary source of your health care coverage? Is it…
#NOCOV121= Without Health Care Coverage Past 12 Months
#MEDSCOS1= Could Not Get Medicine Due To Cost
#MARIJANA= During the past 30 days, on how many days did you use marijuana or hashish?
#RSNMRJNA= What was the reason you used marijuana?
#LCSNUMCG= On average, how many cigarettes do you smoke each day?
#EMTSUPRT= How often get emotional support needed?
#LSATISFY= Satisfaction with life
#SDHSTRES= How often have you felt this kind of stress?
#SXORIENT= Sexual orientation or gender identity
#MSCODE= Metropolitan Status Code
#_RFHLTH= Adults with good or better health
#_PHYS14D= Computed Physical Health Status
#_MENT14D= Computed Mental Health Status
#_HCVU651= Respondents aged 18-64 with health care coverage
#_LTASTH1= Lifetime Asthma Calculated Variable
#_CASTHM1= Current Asthma Calculated Variable
#_ASTHMS1= Computed Asthma Status
#_PRACE1= Computed Preferred Race
#_RACE= Computed Race-Ethnicity grouping
#_AGEG5YR= Reported age in five-year age categories calculated variable
#_AGE65YR= Reported age in two age groups calculated variable
#_AGE_G= Imputed age in six groups
#HTIN4= Computed Height in Inches
#HTM4= Computed Height in Meters
#WTKG3= Computed Weight in Kilograms
#_BMI5= Computed body mass index
#_BMI5CAT= Computed body mass index categories
#_RFBMI5= Overweight or obese calculated variable
#_CHLDCNT= Computed number of children in household
# _EDUCAG= Computed level of education completed categories
#_INCOMG= Computed income categories
#_SMOKER3= Four-level smoker status: Everyday smoker, Someday smoker, Former smoker, Non-smoker
#_RFSMOK3= Adults who are current smokers
#_ECIGSTS= Computed E-cigarette User Status
#_CURECIG= Current E-cigarette User Calculated Variable
#DRNKANY5= Calculated Drink any alcoholic beverages in past 30 days
#DROCDY3_= Computed drink-occasions-per-day
#_RFBING5= Binge Drinking Calculated Variable
#_DRNKWEK= Computed number of drinks of alcohol beverages per week
#_RFDRHV5= Heavy Alcohol Consumption Calculated Variable
#_TOTINDA= Leisure Time Physical Activity Calculated Variable
#ACTIN11_= Estimated Activity Intensity for First Activity
#ACTIN21_= Estimated Activity Intensity for Second Activity
#PADUR1_= Minutes of First Activity
#PADUR2_= Minutes of Second Activity
#PAFREQ1_= Physical Activity Frequency per Week for First Activity
#PAFREQ2_= Physical Activity Frequency per Week for Second Activity
#_MINAC11= Minutes of Physical Activity per week for First Activity
#_MINAC21= Minutes of Physical Activity per week for Second Activity
#STRFREQ_= Strength Activity Frequency per Week
#PAMIN11_= Minutes of Physical Activity per week for First Activity
#PAMIN21_= Minutes of Physical Activity per week for Second Activity
#PA1MIN_= Minutes of total Physical Activity per week
#PAVIG11_= Minutes of Vigorous Physical Activity per week for First Activity
#PAVIG21_= Minutes of Vigorous Physical Activity per week for Second Activity
#PA1VIGM_= Minutes of total Vigorous Physical Activity per week
#_PACAT1= Physical Activity Categories
#_PAINDX1= Physical Activity Index
#_PA150R2= 150 Minute Physical Activity Calculated Variable
#_PA300R2= 300 Minute Physical Activity Calculated Variable
#_PA30021= 300 Minute Physical Activity 2-Level Calculated Variable


#write_csv(brfss_df, '/Users/minhpham1609/Desktop/BRFSS2017.csv')

#https://taxfoundation.org/state-and-local-sales-tax-rates-in-2017/

#In Stratified Sampling, instead of taking samples randomly, we take the data from each group equally. Each of the groups is called Strata.
#The term "data weighting" in most survey-related instances refers to respondent weighting (which in turn weights the data or weights the answers). That is, instead of a respondent counting as one (1) in the cross-tabulations, that respondent might count as 1.25 respondents, or .75 respondents.


#View(brfss_df)






```


```{r}
brfss_df <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2017 main.rds" ) )


#DATA cleaning
glimpse(brfss_df)
colSums(is.na(brfss_df))
which(colSums(is.na(brfss_df))==nrow(brfss_df))
drop_var=which(colSums(is.na(brfss_df))==nrow(brfss_df))

brfss_df=brfss_df[,-drop_var]
dkgenhlth=which(brfss_df$genhlth==7)
brfss_df=filter(brfss_df[-dkgenhlth,])
rfgenhlth=which(brfss_df$genhlth==9)
brfss_df=filter(brfss_df[-rfgenhlth,])

keep_var=c("one"  ,  "xpsu"  ,  "xststr" , "ximprace"  ,  "xllcpwt" , "xstate" , "fmonth" , "imonth" , "iday" ,  "dispcode" , "numadult" , "genhlth" , "physhlth" , 
           "menthlth" , "poorhlth" , "hlthpln1" , "medcost" , "sex" ,  "marital" , "educa" , "employ1" , "children" , "income2" , "decide" , "smoke100" ,  "smokday2" , 
           "stopsmk2" ,  "usenow3" ,  "ecigaret" , "ecignow" , "alcday5" ,   "sleptim1" , "adsleep" , "medicare" ,  "hlthcvr1" , "nocov121" ,  "drvisits" , "medscos1" , 
           "mscode" , "xrfhlth" , "xphys14d" , "xment14d" ,  "xprace1" , "xrace" ,  "xageg5yr" , "xagexg" , "xbmi5" ,  "xbmi5cat" , "xrfbmi5" , "xchldcnt" , 
           "xeducag" , "xincomg" , "xsmoker3","xrfsmok3","xecigsts","xcurecig" , "drnkany5" , "drocdy3x" , "xrfbing5","xment14d","xhcvu651","xtotinda","xdrnkwek"  , 
           "xminac11" , "xminac21" , "strfreqx","income2","cvdcrhd4","harvarth3","asthma3","diabete3"  )

brfss_df17=brfss_df[,keep_var]
str(brfss_df17)

#Other way to keep variable you need

# brfss_df=select(brfss_df,  one  ,  xpsu  ,  xststr , xstrwt , xrawrake ,  xwt2rake , ximprace  ,  xllcpwt , xstate , fmonth , imonth , iday ,  dispcode , 
#         cadult , numadult , genhlth , physhlth , menthlth , poorhlth , hlthpln1 , medcost , asthnow , addepev2 , diabete3 ,  sex ,  marital , educa , veteran3 ,  
#         employ1 , children , income2 , weight2 , height3 , decide , smoke100 ,  smokday2 , stopsmk2 ,  usenow3 ,  ecigaret , ecignow , 
#         alcday5 , avedrnk2 , drnk3ge5 , exerany2 , exeroft1 , exerhmm1 , exeroft2 , exerhmm2 , strength ,   copdsmok ,  sleptim1 , adsleep , medicare ,  hlthcvr1 , 
#         nocov121 ,  drvisits , medscos1 , marijana ,  rsnmrjna , lcsnumcg , emtsuprt ,  lsatisfy , sdhstres , sxorient , mscode , 
#         xrfhlth , xphys14d , xment14d , xhcvu651 ,  xltasth1 , xcasthm1 ,  xasthms1 ,  xprace1 , xrace ,  xageg5yr , xage65yr , xagexg , htin4 , wtkg3 , htm4 , 
#         xbmi5 ,  xbmi5cat , xrfbmi5 , xchldcnt , xeducag , xincomg , xsmoker3 , xrfsmok3 , xecigsts , xcurecig , drnkany5 , drocdy3x , xrfbing5 , xdrnkwek  ,
#         xtotinda , actin11x , actin21x , padur1x , padur2x , pafreq1x , pafreq2x , xminac11 , xminac21 , strfreqx , pamin11x , pamin21x , pa1minx , pavig11x , pavig21x ,
#         pa1vigmx , xpacat1 ,   xpaindx1 , xpa150r2 , xpa300r2 , xpa30021 )


#recode categorical variables
brfss_df17$sex=as.factor(recode(brfss_df17$sex,'1'='M','2'='F',.missing='0',.default = '0'))
str(brfss_df17)

brfss_df17$xrfhlth = as.factor(recode(brfss_df17$xrfhlth, '1' = '1', .default = '0', .missing = '0'))
brfss_df17$xphys14d = as.factor(recode(brfss_df17$xphys14d, '3' = '1', .default = '0', .missing = '0'))
brfss_df17$xment14d = as.factor(recode(brfss_df17$xment14d, '3' = '1', .default = '0', .missing = '0'))
brfss_df17$hcvu651 = as.factor(recode(brfss_df17$xhcvu651, '1' = '1', .default = '0', .missing = '0'))

brfss_df17$xrfsmok3 = as.factor(recode(brfss_df17$xrfsmok3, '2' = '1', .default = '0', .missing = '0'))
brfss_df17$xrfbing5 = as.factor(recode(brfss_df17$xrfbing5, '2' = '1', .default = '0', .missing = '0'))
brfss_df17$xtotinda = as.factor(recode(brfss_df17$xtotinda, '2' = '1', .default = '0', .missing = '0'))

brfss_df17$xrfbmi5 = as.factor(recode(brfss_df17$xrfbmi5, '2' = '1', .default = '0', .missing = '0'))

#recode continuous variable

brfss_df17$xbmi5 <- brfss_df17$xbmi5/100
brfss_df17$children <- replace(x <- brfss_df17$children, x >= 88, 0)
#drink
zz <- brfss_df17 %>% mutate(
alcday5 = case_when(
alcday5 >= 101 & alcday5 <= 107 ~ (alcday5 - 100)*4,
alcday5 >= 201 & alcday5 <= 230 ~ alcday5 - 200,
alcday5 >= 777 ~ 0, 
is.na(alcday5) ~ 0,
)) 
brfss_df17$alcday5 <- zz$alcday5
#demographics
brfss_df17$sex <- as.factor(recode(brfss_df17$sex, "1" = "M", "2" = "F"))
brfss_df17$income2 <- as.factor(recode(brfss_df17$income2, "1" = "le10K", "2" = "10to15K", "3" = "15to20K", "4" = "20to25K", "5" = "25to35K", "6" = "35to50K", "7" = "50to75K", "8" = "gr75K", .default = "NA", missing = "NA"))
brfss_df17$educa <- as.factor(recode(brfss_df17$educa, "1" = "K", "2" = "elem", "3" = "somehs", "4" = "hs_ged", "5" = "some_coll", "6" = "coll_grad", .default = "NA", .missing = "NA")) 
brfss_df17$xageg5yr <- as.factor(recode(brfss_df17$xageg5yr, "1" = "18to24", "2" = "25to29", "3" = "30to34", "4" = "35to39", "5" = "40to44", "6" = "45to49", "7" = "50to54", "8" = "55to59", "9" = "60to64", "10" = "65to69", "11" = "70to74",  "12" = "75to79", "13" = "80+", .default =  "NA", .missing = "NA"))

#setting reference values
brfss_df17$sex <- relevel(brfss_df17$sex, ref = "F")
brfss_df17$income2 <- relevel(brfss_df17$income2, ref = "gr75K")
brfss_df17$educa <- relevel(brfss_df17$educa, ref = "coll_grad")
brfss_df17$xageg5yr <- relevel(brfss_df17$xageg5yr, ref = "18to24")



#State name
brfss_df17$state_name=factor(brfss_df17$xstate , levels = 
                    c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 
                    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 
                    37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 
                    55, 56, 66, 72, 78) ,
                    
                labels = 
                    c("ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", 
                    "COLORADO", "CONNECTICUT", "DELAWARE", "DISTRICT OF COLUMBIA", 
                    "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA",
                    "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND",
                    "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", 
                    "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE",
                    "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", 
                    "NORTH DAKOTA", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA",
                    "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE",
                    "TEXAS", "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON",
                    "WEST VIRGINIA", "WISCONSIN", "WYOMING", "GUAM", "PUERTO RICO",
                    "U.S. VIRGIN ISLANDS"))



### Create date
brfss_df17$iyear <- rep(2017,nrow(brfss_df17)) # make new column
brfss_df17$Date <- as.Date( paste(brfss_df17$iyear, brfss_df17$imonth , brfss_df17$iday , sep = "." )  , format = "%Y.%m.%d" )

brfss_df17=brfss_df17[ ! brfss_df17$dispcode %in% c(1200), ]
brfss_df17=brfss_df17[order(as.Date(brfss_df17$Date, format="%d/%m/%Y")),]


```


#Different survey design function
```{r}
options( survey.lonely.psu = "adjust" )

brfss_design=as_survey_design(.data=brfss_df17,ids="xpsu",strata="xststr",weights="xllcpwt", nest=TRUE)

brfss_design = brfss_df17 %>% as_survey_design(ids="xpsu",strata="xststr",weights="xllcpwt", nest=TRUE)

# I continue to only use brfss_design because it is weighted.
# Think of %>% as 'then'
brfss_design %>% group_by(sex,xrfsmok3)  %>% summarize(proportion =survey_mean(vartype=c("se","ci")))   %>% filter(xrfsmok3==1)


#Write a function to automate the above code: 
library(dplyr)
brfss_function = function(y) { 
  y = enquo(y) 
  brfss_design %>% group_by(sex, !!y) %>% summarize(proportion = survey_mean(vartype=c("se", "ci"))) %>% filter(!!y == 1) %>% 
  cbind(brfss_df17 %>% count(vars = !!y, by = sex) %>% filter(vars == 1))
  }

#Pass each health variable to your new brfss_function function: 
a = brfss_function(xrfhlth)
b = brfss_function(xphys14d)
c = brfss_function(xment14d)
d = brfss_function(hcvu651)
e = brfss_function(xrfbing5)
f = brfss_function(xtotinda)
g = brfss_function(xrfbmi5)


#Bind all those little tables to one large table: 
brfss_function_table = bind_rows(a, b, c, d, e, f, g)

#Set an object to contain the names for the new column, health_variable: 

health_variable = c("xrfhlth", "xphys14d", "xment14d", "hcvu651", "xrfbing5", "xtotinda", "xrfbmi5")

#Add the health_variable column to the brfss_function_table: 
brfss_function_table$health_variable = health_variable

brfss_function_table_2 = subset(brfss_function_table, select=c(health_variable, sex, n, proportion:proportion_upp))


```

```{r}
#Data Visualization
#Plot the data on a bar chart: 
ggplot(data=brfss_function_table_2, aes(x=health_variable, y=proportion, fill=sex)) + geom_bar(stat="identity", position=position_dodge())

#Add error bars: 
ggplot(data=brfss_function_table_2, aes(x=health_variable, y=proportion, fill=sex)) + geom_bar(stat="identity", position=position_dodge()) + geom_errorbar(aes(ymin=proportion_low, ymax=proportion_upp), width = .2, position = position_dodge(.9))

#Flip the coordinates on the bar chart: 
ggplot(data=brfss_function_table_2, aes(x=health_variable, y=proportion, fill=sex)) + geom_bar(stat="identity", position=position_dodge()) + geom_errorbar(aes(ymin=proportion_low, ymax=proportion_upp), width = .2, position = position_dodge(.9)) + coord_flip()


```

```{r}

#Some descriptive statistics
svytable(~xrfhlth + xtotinda, brfss_design)

svychisq(~xrfhlth + xtotinda, brfss_design)

summary(svytable(~xrfhlth + xtotinda, brfss_design))


#GLM Regression. Note family=quasibinomial is for factor variable, family=quasipoisson is for continuous variable
#Logistic Regression

svyglm(xrfhlth~xtotinda, family = quasibinomial, design = brfss_design)
summary(svyglm(xrfhlth~xtotinda, family = quasibinomial, design = brfss_design))

#Odd Ratio = or
or = svyglm(xrfhlth~xtotinda, family = quasibinomial, design = brfss_design)
summary(or)
confint(or)  #confidence interval
exp(coef(or)) #This show the true odd ratio

exp(cbind(OR = coef(or), confint(or)))

#building a table
or_table = exp(cbind(OR = coef(or), confint(or)))[2, ]
or_table$hv = c("xtotinda")
unlist(or_table)
as.data.frame(or_table)

or = svyglm(xrfhlth~ xtotinda, family = quasibinomial, design = brfss_design)

#function for all other variables
or_fun = function(y) {
  or_table = exp(cbind(OR = coef(or), confint(or)))[2, ]
  or_table$hv = c(y)
  unlist(or_table)
  as.data.frame(or_table)
}

a = or_fun("xtotinda")

or = svyglm(xrfhlth~ xagexg, family = quasibinomial, design = brfss_design)
b = or_fun("xagexg")

or = svyglm(xrfhlth~ xrfsmok3, family = quasibinomial, design = brfss_design)
c = or_fun("X_RFSMOK3")

or = svyglm(xrfhlth~ hcvu651, family = quasibinomial, design = brfss_design)
d = or_fun("X_HCVU651")

or = svyglm(xrfhlth~ sex, family = quasibinomial, design = brfss_design)
e = or_fun("sex")

or = svyglm(xrfhlth~ income2, family = quasibinomial, design = brfss_design)
f = or_fun("income2")

or = svyglm(xrfhlth~ educa, family = quasibinomial, design = brfss_design)
g = or_fun("educa")

or = svyglm(xrfhlth~ xrfbmi5, family = quasibinomial, design = brfss_design)
h = or_fun("xrfbmi5")


all_or = bind_rows(a, b, c, d, e, f, g, h)
all_or = as.data.frame(all_or)
alr = svyglm(xrfhlth ~ xtotinda + xagexg + xrfsmok3 + hcvu651 + sex + income2 + educa + xrfbmi5, family = quasibinomial, design = brfss_design)
summary(alr)
confint(alr)
exp(coef(alr))
exp(cbind(AOR = coef(alr), confint(alr)))
exp(cbind(AOR = coef(alr), confint(alr)))[-1, ]
adj_or = exp(cbind(AOR = coef(alr), confint(alr)))[-1, ]
adj_or = as.data.frame(adj_or)
bind_cols(all_or, adj_or)
table1 = bind_cols(all_or, adj_or)
colnames(table1)
table1 = table1 %>% select("hv", "OR", "X2.5..", "X97.5..", "AOR", "2.5 %", "97.5 %") #hv=health variables, or=odd ratio, aor=adjusted odd ratio
table1$orll = table1$X2.5..
table1$orul = table1$X97.5..
table1$aorll = table1$"2.5 %"
table1$aorul = table1$"97.5 %"
table1 = table1 %>% select(hv, OR, orll, orul, AOR, aorll, aorul)


```

```{r}
#Some vidualization
ggplot(table1, aes(x=hv, y = OR)) + geom_bar(stat = "identity", position = "dodge")
ggplot(table1, aes(x=hv, y = OR)) + geom_bar(stat = "identity", position = "dodge") + geom_abline(slope = 0, intercept = 1)
ggplot(table1, aes(x=hv, y = OR)) + geom_bar(stat = "identity", position = "dodge") + geom_abline(slope = 0, intercept = 1, color = "red")
ggplot(table1, aes(x=hv, y = OR)) + geom_bar(stat = "identity", position = "dodge") + geom_abline(slope = 0, intercept = 1, color = "red", size = 2) + geom_errorbar(aes(ymin=orll, ymax=orul), width = .2, position = position_dodge(.9))
ggplot(table1, aes(x=hv, y = AOR)) + geom_bar(stat = "identity", position = "dodge") + geom_abline(slope = 0, intercept = 1, color = "red", size = 2) + geom_errorbar(aes(ymin=aorll, ymax=aorul), width = .2, position = position_dodge(.9))

ORtable = table1 %>% select(hv, OR, orll, orul)
ORtable$type = c("OR")
ORtable$stat = ORtable$OR
ORtable$ll = ORtable$orll
ORtable$ul = ORtable$orul
ORtable = ORtable %>% select(hv, stat, type, ll, ul)
AORtable = table1 %>% select(hv, AOR, aorll, aorul)
AORtable$type = c("AOR")
AORtable$stat = AORtable$AOR
AORtable$ll = AORtable$aorll
AORtable$ul = AORtable$aorul
AORtable = AORtable %>% select(hv, stat, type, ll, ul)
table2 = rbind(ORtable, AORtable)

figureoraor = ggplot(table2, aes(x=hv, y = stat, fill = type)) + geom_bar(stat = "identity", position = "dodge") + geom_abline(slope = 0, intercept = 1, color = "red", size = 2) + geom_errorbar(aes(ymin=ll, ymax=ul), width = .2, position = position_dodge(.9))
print(figureoraor + ggtitle("OR & AOR"))


```






















```{r}
#Descriptive Statistics

#install.packages("stargazer")
#https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf

library(stargazer)
stargazer(brfss_df) #quite good for descriptive statistics

#install.packages("texreg")
library(textreg)
# stargazer doesn't do survey, or lm4 regression Latex table.
# Try "texreg" for Latex table for lme4
# https://cran.r-project.org/web/packages/texreg/vignettes/texreg.pdf

svyby( ~ couldnt_see_doc_due_to_cost , ~ state_name , brfss_design , svymean )

hist(brfss_design$variables$menthlth)

library(lme4)

glm_result <- 
    svyglm( 
        days_of_bad_mental_health ~ healthcare_coverage + couldnt_see_doc_due_to_cost , 
        brfss_design 
    )

summary( glm_result )
#stargazer(glm_result, title="Results", align=TRUE)
#screenreg(glm_result)
# Can't do this screenreg table yet because it needs to be run with lm4 regression first


#Check to see if student debt data is available and maybe do "student debt on mental health"





```




















