---
title: "TEST_1"
author: "Minh Pham"
date: "03/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE, echo=FALSE}
library(readr)
library(pscl)
library(spdep)
library(MASS)
library(readxl)
library(lodown)
library(tidyverse)
library(survey)
library(zoo)
library(dplyr)
library(srvyr)
library(ggplot2)
library(sjstats)
library(quantmod)
library(multiwayvcov)
library(InformationValue)
library(lmtest)
library(mpath)
library(rsq)
library(stargazer)
```




```{r, echo=F}
brfss_df13 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2013 main.rds" ) )
brfss_df14 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2014 main.rds" ) )
brfss_df15 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2015 main.rds" ) )
brfss_df16 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2016 main.rds" ) )
brfss_df17 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2017 main.rds" ) )
brfss_df18 <- 
    readRDS( file.path( path.expand( "~" ) , "BRFSS" , "2018 main.rds" ) )


brfss_df13$xpsu=as.integer(brfss_df13$xpsu)
brfss_df14$xpsu=as.integer(brfss_df14$xpsu)
brfss_df15$xpsu=as.integer(brfss_df15$xpsu)
brfss_df16$xpsu=as.integer(brfss_df16$xpsu)
brfss_df17$xpsu=as.integer(brfss_df17$xpsu)
brfss_df18$xpsu=as.integer(brfss_df18$xpsu)

### Create date
brfss_df13$iyear <- rep(2013,nrow(brfss_df13)) # make new column
brfss_df13$Date <- as.Date( paste(brfss_df13$iyear, brfss_df13$imonth , brfss_df13$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df13=brfss_df13[order(as.Date(brfss_df13$Date, format="%d/%m/%Y")),]

brfss_df14$iyear <- rep(2014,nrow(brfss_df14)) # make new column
brfss_df14$Date <- as.Date( paste(brfss_df14$iyear, brfss_df14$imonth , brfss_df14$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df14=brfss_df14[order(as.Date(brfss_df14$Date, format="%d/%m/%Y")),]

brfss_df15$iyear <- rep(2015,nrow(brfss_df15)) # make new column
brfss_df15$Date <- as.Date( paste(brfss_df15$iyear, brfss_df15$imonth , brfss_df15$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df15=brfss_df15[order(as.Date(brfss_df15$Date, format="%d/%m/%Y")),]

brfss_df16$iyear <- rep(2016,nrow(brfss_df16)) # make new column
brfss_df16$Date <- as.Date( paste(brfss_df16$iyear, brfss_df16$imonth , brfss_df16$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df16=brfss_df16[order(as.Date(brfss_df16$Date, format="%d/%m/%Y")),]

brfss_df17$iyear <- rep(2017,nrow(brfss_df17)) # make new column
brfss_df17$Date <- as.Date( paste(brfss_df17$iyear, brfss_df17$imonth , brfss_df17$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df17=brfss_df17[order(as.Date(brfss_df17$Date, format="%d/%m/%Y")),]

brfss_df18$iyear <- rep(2018,nrow(brfss_df18)) # make new column
brfss_df18$Date <- as.Date( paste(brfss_df18$iyear, brfss_df18$imonth , brfss_df18$iday , sep = "." )  , format = "%Y.%m.%d" )
brfss_df18=brfss_df18[order(as.Date(brfss_df18$Date, format="%d/%m/%Y")),]

brfss_df18$sex=brfss_df18$sex1


brfss_df1314 <- intersect(colnames(brfss_df13), colnames(brfss_df14))

brfss_df1314 <- rbind(brfss_df13[ , brfss_df1314], brfss_df14[ , brfss_df1314])

brfss_df131415 <- intersect(colnames(brfss_df1314), colnames(brfss_df15))

brfss_df131415 <- rbind(brfss_df1314[ , brfss_df131415], brfss_df15[ , brfss_df131415])

brfss_df13141516 <- intersect(colnames(brfss_df131415), colnames(brfss_df16))

brfss_df13141516 <- rbind(brfss_df131415[ , brfss_df13141516], brfss_df16[ , brfss_df13141516])

brfss_df1314151617 <- intersect(colnames(brfss_df13141516), colnames(brfss_df17))

brfss_df1314151617 <- rbind(brfss_df13141516[ , brfss_df1314151617], brfss_df17[ , brfss_df1314151617])

brfss_df131415161718 <- intersect(colnames(brfss_df1314151617), colnames(brfss_df18))

brfss_df131415161718 <- rbind(brfss_df1314151617[ , brfss_df131415161718], brfss_df18[ , brfss_df131415161718])

#write_csv(brfss_df131415161718, '/Users/minhpham1609/Desktop/brfss_df131415161718.csv')

# Var-names: xstate	fmonth	imonth	iday	iyear	dispcode	xpsu	pvtresd1	colghous	ladult	numadult	nummen	numwomen	genhlth	physhlth	menthlth	poorhlth	hlthpln1	persdoc2	medcost	checkup1	cvdinfr4	cvdcrhd4	cvdstrk3	asthma3	asthnow	chcscncr	chcocncr	chccopd1	havarth3	addepev2	diabete3	veteran3	marital	children	educa	employ1	income2	weight2	height3	renthom1	sex	pregnant	blind	decide	diffwalk	diffdres	diffalon	smoke100	smokday2	stopsmk2	lastsmk2	usenow3	alcday5	avedrnk2	drnk3ge5	maxdrnks	exerany2	seatbelt	flushot6	flshtmy2	hivtst6	hivtstd3	pdiabtst	prediab1	diabage2	insulin	bldsugar	doctdiab	chkhemo3	feetchk	diabeye	diabedu	imfvplac	hpvadvc2	hpvadsht	rcsgendr	rcsrltn2	casthdx2	casthno2	ctelnum1	cadult	cclghous	landline	qstver	qstlang	mscode	xststr	xstrwt	xrawrake	xwt2rake	xchispnc	xcrace1	xcllcpwt	xdualuse	xdualcor	xllcpwt	xrfhlth	xhcvu651	xltasth1	xcasthm1	xasthms1	xdrdxar1	xprace1	xmrace1	xhispanc	xrace	xraceg21	xracegr3	xracexg1	xageg5yr	xage65yr	xagexg	htin4	htm4	wtkg3	xbmi5	xbmi5cat	xrfbmi5	xchldcnt	xeducag	xincomg	xsmoker3	xrfsmok3	drnkany5	drocdy3x	xrfbing5	xtotinda	xrfseat2	xrfseat3	xflshot6	xaidtst3	xage80	one	Date

#first let’s select a couple variables

brfss_df131415161718$state_name=factor(brfss_df131415161718$xstate , levels = 
                    c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 
                    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 
                    37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 
                    55, 56) ,
                    
                labels = 
                    c("ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", 
                    "COLORADO", "CONNECTICUT", "DELAWARE", "DISTRICT OF COLUMBIA", 
                    "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA",
                    "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND",
                    "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", 
                    "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE",
                    "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", 
                    "NORTH DAKOTA", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA",
                    "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE",
                    "TEXAS", "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON",
                    "WEST VIRGINIA", "WISCONSIN", "WYOMING"))


brfss_df131415161718s= brfss_df131415161718 %>% select(xstate,	fmonth,	imonth,	iday,	iyear,	dispcode,	xpsu,	physhlth,	menthlth,	marital,	employ1,	sex,	xststr,	xstrwt,	xllcpwt,	xprace1,	xagexg,	xchldcnt,	xeducag,	xincomg,	Date,	state_name  ) 

```

```{r, include=FALSE, echo=FALSE}
returns.lag <- read.csv("~/Desktop/lagreturns.csv")

returns.lag$date= as.Date(returns.lag$date, format = "%m/%d/%y")
returns.lag$date= as.Date(returns.lag$date, format = "%Y-%m-%d")

plot(returns.lag$date,returns.lag$X30returns, type = "l")
plot(returns.lag$date,returns.lag$halfmonthreturns, type = "l")
plot(returns.lag$date,returns.lag$X1weekreturns, type = "l")


brfss_df131415161718s$date=brfss_df131415161718s$Date
brfss_df131415161718s$date=as.Date(brfss_df131415161718s$date, "%Y-%m-%d")


```

```{r}
#DATA cleaning:

#recode main outcome 

brfss_df131415161718s$mental_health_recode = ifelse( brfss_df131415161718s$menthlth %in% 1:30 , as.numeric( brfss_df131415161718s$menthlth), NA)
brfss_df131415161718s$mental_health_recode = replace(brfss_df131415161718s$mental_health_recode, brfss_df131415161718s$mental_health_recode <15,1)
brfss_df131415161718s$mental_health_recode= replace(brfss_df131415161718s$mental_health_recode, brfss_df131415161718s$mental_health_recode >=15,0)

brfss_df131415161718s$physical_health_recode = ifelse( brfss_df131415161718s$physhlth %in% 1:30 , as.numeric( brfss_df131415161718s$physhlth), NA)
brfss_df131415161718s$physical_health_recode = replace(brfss_df131415161718s$physical_health_recode, brfss_df131415161718s$physical_health_recode <15,1)
brfss_df131415161718s$physical_health_recode = replace(brfss_df131415161718s$physical_health_recode, brfss_df131415161718s$physical_health_recode >=15,0)


#demographics
brfss_df131415161718s$gender= ifelse( brfss_df131415161718s$sex ==1 , 1, ifelse(brfss_df131415161718s$sex==2, 0, NA))

brfss_df131415161718s$number_of_children <-  ifelse( brfss_df131415161718s$xchldcnt ==1 , 1, ifelse(brfss_df131415161718s$xchldcnt==2, 2,ifelse(brfss_df131415161718s$xchldcnt==3,3,ifelse(brfss_df131415161718s$xchldcnt==4,4,ifelse(brfss_df131415161718s$xchldcnt==5,5,ifelse(brfss_df131415161718s$xchldcnt==6,6,ifelse(brfss_df131415161718s$xchldcnt==9,9, NA)))))))

brfss_df131415161718s$marital_status <-  ifelse( brfss_df131415161718s$marital ==1 , 1, ifelse(brfss_df131415161718s$marital==2, 2,ifelse(brfss_df131415161718s$marital==3,3,ifelse(brfss_df131415161718s$marital==4,4,ifelse(brfss_df131415161718s$marital==5,5,ifelse(brfss_df131415161718s$marital==6,6, ifelse(brfss_df131415161718s$marital==9,9, NA)))))))

brfss_df131415161718s$employment_status <- ifelse( brfss_df131415161718s$employ1 ==1 , 1, ifelse(brfss_df131415161718s$employ1==2, 2,ifelse(brfss_df131415161718s$employ1==3,3,ifelse(brfss_df131415161718s$employ1==4,4,ifelse(brfss_df131415161718s$employ1==5,5,ifelse(brfss_df131415161718s$employ1==6,6,ifelse(brfss_df131415161718s$employ1==7,7,ifelse(brfss_df131415161718s$employ1==8,8,ifelse(brfss_df131415161718s$employ1==9,9, NA)))))))))

brfss_df131415161718s$calculated_race <- ifelse( brfss_df131415161718s$xprace1 ==1 , 1, ifelse(brfss_df131415161718s$xprace1==2, 2,ifelse(brfss_df131415161718s$xprace1==3,3,ifelse(brfss_df131415161718s$xprace1==4,4,ifelse(brfss_df131415161718s$xprace1==5,5,ifelse(brfss_df131415161718s$xprace1==6,6,ifelse(brfss_df131415161718s$xprace1==7,7, ifelse(brfss_df131415161718s$xprace1==77,8, ifelse(brfss_df131415161718s$xprace1==99,8, NA)))))))))

brfss_df131415161718s$calculated_education <-ifelse( brfss_df131415161718s$xeducag ==1 , 1, ifelse(brfss_df131415161718s$xeducag==2, 2,ifelse(brfss_df131415161718s$xeducag==3,3,ifelse(brfss_df131415161718s$xeducag==4,4,ifelse(brfss_df131415161718s$xeducag==9,9, NA)))))


brfss_df131415161718s$calculated_income <- ifelse( brfss_df131415161718s$xincomg ==1 , 1, ifelse(brfss_df131415161718s$xincomg==2, 2,ifelse(brfss_df131415161718s$xincomg==3,3,ifelse(brfss_df131415161718s$xincomg==4,4,ifelse(brfss_df131415161718s$xincomg==5,5,ifelse(brfss_df131415161718s$xincomg==9,9, NA))))))

brfss_df131415161718s$calculated_age <- ifelse( brfss_df131415161718s$xagexg ==1 , 1, ifelse(brfss_df131415161718s$xagexg==2, 2,ifelse(brfss_df131415161718s$xagexg==3,3,ifelse(brfss_df131415161718s$xagexg==4,4,ifelse(brfss_df131415161718s$xagexg==5,5,ifelse(brfss_df131415161718s$xagexg==6,6,NA))))))


brfss_df131415161718s=na.omit(brfss_df131415161718s)
colSums(is.na(brfss_df131415161718s))


```

```{r}
BRFSS_FINANCE_data= merge(returns.lag,brfss_df131415161718s, by="date")

BRFSS_FINANCE_data= BRFSS_FINANCE_data %>% select(imonth,	iyear,	dispcode,	xpsu,	gender,	number_of_children,	marital_status,	employment_status,	xststr,	xstrwt,	xllcpwt,	calculated_race,	calculated_education,	calculated_income,	calculated_age,	date,	state_name, VIX.Adjusted, SPY.Adjusted, SPY.rets, X30returns, halfmonthreturns, X1weekreturns, vix30returns, vixhalfmonthreturns, vix1weekreturns, mental_health_recode, physical_health_recode ) 

#getting rid of incomlete respondents
BRFSS_FINANCE_data=BRFSS_FINANCE_data[ ! BRFSS_FINANCE_data$dispcode %in% c(1200), ]

#getting rid of duplicates
BRFSS_FINANCE_data=BRFSS_FINANCE_data[order(BRFSS_FINANCE_data$xpsu),]
BRFSS_FINANCE_data=BRFSS_FINANCE_data %>% distinct(xpsu, .keep_all = TRUE)

colSums(is.na(BRFSS_FINANCE_data))



BRFSS_FINANCE_data=na.omit(BRFSS_FINANCE_data)


```


```{r}
# RECODE FINAL

#DEMOGRAPHICS
BRFSS_FINANCE_data$gender=as.factor(recode(BRFSS_FINANCE_data$gender,'1'='male','0'='female',.missing='NA',.default = 'NA'))

BRFSS_FINANCE_data$number_of_children <- as.factor(recode(BRFSS_FINANCE_data$number_of_children, "1" = "nochildren", "2" = "1children", "3" = "2children", "4" = "3children", "5" = "4children", "6" = "5morechildren", "9"="others", .default =  "NA", .missing = "NA"))

BRFSS_FINANCE_data$marital_status <- as.factor(recode(BRFSS_FINANCE_data$marital_status, "1" = "married", "2" = "divorced","3"="widowed","4"="separated","5"="nevermarried","6"="membermarriedcoup","9"="refused",.default = "NA", .missing = "NA"))

BRFSS_FINANCE_data$employment_status <- as.factor(recode(BRFSS_FINANCE_data$employment_status, "1" = "wagesemployed", "2" = "selfemployed","3"="noworkmore1","4"="noworkless1","5"="homemaker","6"="student","7"="retired","8"="unable", "9"="refused",.default = "NA", .missing = "NA"))

BRFSS_FINANCE_data$calculated_race <- as.factor(recode(BRFSS_FINANCE_data$calculated_race, "1" = "white", "2" = "black","3"="native","4"="asian","5"="pacific","6"="other", "7"="nopreferred", "8"="others" ,.default = "NA", .missing = "NA"))

BRFSS_FINANCE_data$calculated_education <- as.factor(recode(BRFSS_FINANCE_data$calculated_education, "1" = "K", "2" = "HSgrad", "3" = "attendCOL", "4" = "COLgrad", "9"="others", .default = "NA", .missing = "NA")) 

BRFSS_FINANCE_data$calculated_income <- as.factor(recode(BRFSS_FINANCE_data$calculated_income, "1" = "le15K", "2" = "15to25K", "3" = "25to35K", "4" = "35to50K", "5" = "50more","9"="others", .default = "NA", missing = "NA"))

BRFSS_FINANCE_data$calculated_age <- as.factor(recode(BRFSS_FINANCE_data$calculated_age, "1" = "18to24", "2" = "25to34", "3" = "35to44", "4" = "45to54", "5" = "55to64", "6" = "65older", .default =  "NA", .missing = "NA"))

#setting reference values
BRFSS_FINANCE_data$gender <- relevel(BRFSS_FINANCE_data$gender, ref = "female")
BRFSS_FINANCE_data$calculated_income <- relevel(BRFSS_FINANCE_data$calculated_income, ref = "50more")
BRFSS_FINANCE_data$calculated_education <- relevel(BRFSS_FINANCE_data$calculated_education, ref = "COLgrad")
BRFSS_FINANCE_data$calculated_age <- relevel(BRFSS_FINANCE_data$calculated_age, ref = "18to24")
BRFSS_FINANCE_data$marital_status = relevel(BRFSS_FINANCE_data$marital_status, ref = "married")
BRFSS_FINANCE_data$employment_status = relevel(BRFSS_FINANCE_data$employment_status, ref = "wagesemployed")
BRFSS_FINANCE_data$calculated_race = relevel(BRFSS_FINANCE_data$calculated_race, ref = "white")
BRFSS_FINANCE_data$number_of_children = relevel(BRFSS_FINANCE_data$number_of_children, ref = "nochildren")

#year and state dummies
BRFSS_FINANCE_data$iyear = as.factor(BRFSS_FINANCE_data$iyear)
BRFSS_FINANCE_data$imonth = as.factor(BRFSS_FINANCE_data$imonth)
BRFSS_FINANCE_data$state_name = as.factor(BRFSS_FINANCE_data$state_name)

#state-specific-time trends
BRFSS_FINANCE_data$yearmonth=as.yearmon( paste(BRFSS_FINANCE_data$iyear, BRFSS_FINANCE_data$imonth, sep = "." )  , format = "%Y.%m" )
BRFSS_FINANCE_data$yearmonth = as.factor(BRFSS_FINANCE_data$yearmonth)

#check the data
check_BRFSS_FINANCE_data=BRFSS_FINANCE_data[order(BRFSS_FINANCE_data$xpsu),]
check_BRFSS_FINANCE_data=BRFSS_FINANCE_data[order(BRFSS_FINANCE_data$date),]

#write_csv(check_BRFSS_FINANCE_data, '/Users/minhpham1609/Desktop/check_BRFSS_FINANCE_data.csv')

```


```{r}

# BINARY OUCOMES mental_health_recode with 1 being good mental health, as the model predicting 1, or good health, we would expect a positive effect, or the probability of SPY increase and having good mental health will increase compared to bad mental health

#logit
table(BRFSS_FINANCE_data$mental_health_recode)
# Create Training Data
input_ones <- BRFSS_FINANCE_data[which(BRFSS_FINANCE_data$mental_health_recode == 1), ]  # all 1's
input_zeros <- BRFSS_FINANCE_data[which(BRFSS_FINANCE_data$mental_health_recode == 0), ]  # all 0's
set.seed(100)  # for repeatability of samples # reducing this number will reduce the estimates
input_zeros_training_rows <- sample(1:nrow(input_zeros), 0.7*nrow(input_zeros)) 
input_ones_training_rows <- sample(1:nrow(input_ones), 0.7*nrow(input_zeros))  

training_ones <- input_ones[input_ones_training_rows, ]  
training_zeros <- input_zeros[input_zeros_training_rows, ]
trainingData <- rbind(training_ones, training_zeros)  # row bind the 1's and 0's 
table(trainingData$mental_health_recode)

# Create Test Data
test_ones <- input_ones[-input_ones_training_rows, ]
test_zeros <- input_zeros[-input_zeros_training_rows, ]
testData <- rbind(test_ones, test_zeros)  # row bind the 1's and 0's 
table(testData$mental_health_recode)

#model
test.lm = glm(mental_health_recode ~ 0 + X30returns + calculated_age + gender + calculated_income + calculated_education + marital_status + number_of_children+ employment_status + calculated_race +state_name +state_name*(as.numeric(yearmonth)) + imonth + iyear, weights=xstrwt, family=binomial(link=logit),    data = trainingData)
sum_test.lm=summary(test.lm)
sum_test.lm

predicted <- plogis(predict(test.lm, testData))
predicted <- predict(test.lm, testData, type="response") 
optCutOff <- optimalCutoff(testData$mental_health_recode, predicted)[1] 
misClassError(testData$mental_health_recode, predicted, threshold = optCutOff)
plotROC(testData$mental_health_recode, predicted)  #0.7, which is pretty good
Concordance(testData$mental_health_recode, predicted)
sensitivity(testData$mental_health_recode, predicted, threshold = optCutOff) #sensitivity is low because false negative is too high
specificity(testData$mental_health_recode, predicted, threshold = optCutOff) #specificity is high because false positive is too low
confusionMatrix(testData$mental_health_recode, predicted, threshold = optCutOff)




# BINARY OUCOMES physical_health_recode with 1 being good physical health, we don't expect this to be significant.

#logit
table(BRFSS_FINANCE_data$physical_health_recode)
# Create Training Data
input_ones <- BRFSS_FINANCE_data[which(BRFSS_FINANCE_data$physical_health_recode == 1), ]  # all 1's
input_zeros <- BRFSS_FINANCE_data[which(BRFSS_FINANCE_data$physical_health_recode == 0), ]  # all 0's
set.seed(250)  # for repeatability of samples
input_zeros_training_rows <- sample(1:nrow(input_zeros), 0.7*nrow(input_zeros)) 
input_ones_training_rows <- sample(1:nrow(input_ones), 0.7*nrow(input_zeros))  

training_ones <- input_ones[input_ones_training_rows, ]  
training_zeros <- input_zeros[input_zeros_training_rows, ]
trainingData <- rbind(training_ones, training_zeros)  # row bind the 1's and 0's 
table(trainingData$physical_health_recode)

# Create Test Data
test_ones <- input_ones[-input_ones_training_rows, ]
test_zeros <- input_zeros[-input_zeros_training_rows, ]
testData <- rbind(test_ones, test_zeros)  # row bind the 1's and 0's 
table(testData$physical_health_recode)

#model
test.lm = glm(physical_health_recode ~ 0 + X30returns + calculated_age + gender + calculated_income + calculated_education + marital_status + number_of_children+ employment_status + calculated_race +state_name +state_name*(as.numeric(yearmonth)) + imonth + iyear, weights=xstrwt, family=binomial(link=logit),    data = trainingData)
sum_test.lm=summary(test.lm)
sum_test.lm

#predicted <- plogis(predict(test.lm, testData))
predicted <- predict(test.lm, testData, type="response") 
optCutOff <- optimalCutoff(testData$physical_health_recode, predicted)[1] 
misClassError(testData$physical_health_recode, predicted, threshold = optCutOff)
plotROC(testData$physical_health_recode, predicted)  #0.7, which is pretty good
Concordance(testData$physical_health_recode, predicted)
sensitivity(testData$physical_health_recode, predicted, threshold = optCutOff) #sensitivity is low because false negative is too high
specificity(testData$physical_health_recode, predicted, threshold = optCutOff) #specificity is high because false positive is too low
confusionMatrix(testData$physical_health_recode, predicted, threshold = optCutOff)


```



